[workspace]
resolver = "2"
members = [
    "bh-jws-utils",
    "bh-sd-jwt",
    "bh-status-list",
    "bh-uri-utils",
    "bherror",
    "bhmdoc",
    "bhx5chain",
]

[profile.ci]
inherits = "dev"
debug = false
