[graph]
targets = [
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-pc-windows-gnu" },
    { triple = "arm64e-apple-darwin" },
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "Unicode-DFS-2016",
]

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = []

[bans]
multiple-versions = "allow"

deny = []

skip-tree = []
