[graph]
targets = [
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-pc-windows-gnu" },
    { triple = "arm64e-apple-darwin" },
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]

exceptions = [
    # We publish our crates under AGPLv3
    { crate = "bh-jws-utils", allow = ["AGPL-3.0"] },
    { crate = "bh-sd-jwt", allow = ["AGPL-3.0"] },
    { crate = "bh-status-list", allow = ["AGPL-3.0"] },
    { crate = "bh-uri-utils", allow = ["AGPL-3.0"] },
    { crate = "bherror", allow = ["AGPL-3.0"] },
    { crate = "bhmdoc", allow = ["AGPL-3.0"] },
    { crate = "bhx5chain", allow = ["AGPL-3.0"] },
]

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    # unmaintained
    "RUSTSEC-2024-0370", # `proc-macro-error`, possibly introduced by `iref v3.2.2`
]

[bans]
multiple-versions = "allow"

deny = []

skip-tree = []
